apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-policies-example-pets
  namespace: custom-policies
  labels:
    subscription-pause: "false"
  annotations:
    apps.open-cluster-management.io/github-path: policies/example/overlays/pets
    apps.open-cluster-management.io/github-branch: new-api-version
spec:
  channel: custom-policies/acm-gitops-github
  placement:
    local: true
#  timewindow:
#    windowtype: "active"
#    location: "America/Los_Angeles"
#    daysofweek: [ "Friday", "Saturday", "Sunday" ]
#    hours:
#      - start: "05:00PM"
#        end: "10:00PM"