apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-registry-pvc-nfs
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-registry-pvc-nfs
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["custom-policies"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: PersistentVolumeClaim
                metadata:
                  name: image-registry-pvc
                  namespace: openshift-image-registry
                spec:
                  accessModes:
                    - ReadWriteMany
                  resources:
                    requests:
                      storage: 100Gi
                  volumeMode: Filesystem
