apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-registry-nfs
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-registry-nfs
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["custom-policies"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: PersistentVolume
                metadata:
                  name: registry-pv
                spec:
                  accessModes:
                    - ReadWriteMany
                  capacity:
                      storage: 100Gi
                  nfs:
                    path: /export
                    server: 192.168.1.238
                  persistentVolumeReclaimPolicy: Retain
                  volumeMode: Filesystem
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: PersistentVolumeClaim
                metadata:
                  name: image-registry-pvc
                  namespace: openshift-image-registry
                spec:
                  accessModes:
                    - ReadWriteMany
                  resources:
                    requests:
                      storage: 100Gi
                  volumeMode: Filesystem
                  storageClassName: ""
            - complianceType: musthave
              objectDefinition:
                apiVersion: imageregistry.operator.openshift.io/v1
                kind: Config
                metadata:
                  name: cluster
                spec:
                   replicas: 2
                   storage:
                     pvc:
                       claim: image-registry-pvc
 
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-registry-nfs
placementRef:
  name: placement-policy-registry-nfs
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-registry-nfs
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-registry-nfs
spec:
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - lab
