apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-demo
  annotations:
    policy.open-cluster-management.io/standards: MyStandards
    policy.open-cluster-management.io/categories: MyCategories
    policy.open-cluster-management.io/controls: MyControls
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-demo-namespaces
        spec:
          remdiationAction: inform
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["custom-policies"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1             
                kind: Namespace
                metadata:
                  name: project-one
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: project-two
