apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-label-infra-nodes
  namespace: custom-policies
  #annotations:
  #  policy.open-cluster-management.io/standards: 
  #  policy.open-cluster-management.io/categories: 
  #  policy.open-cluster-management.io/controls: 
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-label-infra-nodes
        spec:
          remediationAction: inform
          severity: medium
          namespaceSelector:
            exclude: [""]
            include: ["*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Node
                name: infra1
                metadata:
                    labels:
                      node-role.kubernetes.io/infra: ""
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Node
                name: infra1
                metadata:
                    labels:
                      node-role.kubernetes.io/worker: ""
