apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-migrate-router
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-migrate-router
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - openshift-ingress-operator
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.openshift.io/v1
            kind: IngressController
            metadata:
              name: default
            spec:
              nodePlacement:
                nodeSelector:
                  matchLabels:
                    node-role.kubernetes.io/dev: "" # testing 
              tolerations:
                - effect: NoSchedule
                  key: node-function
                  operator: Exists
        remediationAction: enforce
        severity: low
  remediationAction: enforce
