apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-migrate-metrics
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-migrate-metrics
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - openshift-monitoring
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: cluster-monitoring-config
            data:
              config.yaml: |+
                alertmanagerMain:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                prometheusK8s:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                prometheusOperator:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                grafana:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                k8sPrometheusAdapter:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                kubeStateMetrics:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
                telemeterClient:
                  tolerations:
                    - key: node-function
                      operator: Exists
                      effect: NoSchedule
                  nodeSelector:
                    node-role.kubernetes.io/infra: ""
        remediationAction: enforce
        severity: low
