apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-namespace-custom
  namespace: custom-policies
  annotations:
    policy.open-cluster-management.io/standards: 
    policy.open-cluster-management.io/categories: 
    policy.open-cluster-management.io/controls: 
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  policy-templates:
    - complianceType: musthave
      objectDefinition:
        kind: Namespace 
        apiVersion: v1
        metadata:
          name: project-one
    - complianceType: mustnothave
      objectDefinition:
        kind: Namespace 
        apiVersion: v1
        metadata:
          name: project-two