apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-identity-provider
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-identity-provider
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - *
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: google-secret
              namespace: openshift-config
            type: Opaque
            data:
              clientSecret: '' 
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: OAuth
            metadata:
              name: cluster
            spec: 
             apiVersion: config.openshift.io/v1
             kind: OAuth
             metadata:
               name: cluster
             spec:
               identityProviders:
               - name: google
                 mappingMethod: claim
                 type: Google
                 google:
                   clientID: ''
                   clientSecret:
                     name: google-secret
                   hostedDomain: "redhat.com"
        remediationAction: enforce
        severity: low
  remediationAction: enforce
