apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-registry-pv-nfs
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-registry-pv-nfs
      spec:
        remediationAction: inform
        severity: low
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - *
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: PersistentVolume
            metadata:
              name: registry-pv
            spec:
              accessModes:
                - ReadWriteMany
              capacity:
                  storage: 100Gi
              nfs:
                path: /export
                server: 192.168.1.238
              persistentVolumeReclaimPolicy: Retain
