apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-example
spec:
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-example-namespaces
      spec:
        remediationAction: inform
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["custom-policies"]
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1             
            kind: Namespace
            metadata:
              name: project-dog
        - complianceType: mustnothave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: project-cat