apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-namespace-custom
spec:
  policy-templates:
    - complianceType: musthave
      objectDefinition:
        kind: Namespace 
        apiVersion: v1
        metadata:
          name: project-fish
