apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-disable-master-scheduling
spec:
  clusterSelector:
    matchExpressions:
      - {key: cloud, operator: In, values: ["Amazon"]}