apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-disable-master-scheduling
  annotations:
    policy.open-cluster-management.io/standards: 
    policy.open-cluster-management.io/categories: 
    policy.open-cluster-management.io/controls: 
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-scheduling
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["custom-policies"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Scheduler
                metadata:
                  name: cluster
                spec:
                  mastersSchedulable: true
                  policy:
                    name: ""