apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-infra-nodes
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-infra-nodes
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["custom-policies"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Node
                metadata:
                  name: worker-0
                  labels:
                    node-role.kubernetes.io/infra: ""
                    node-role.kubernetes.io/worker-:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Node
                metadata:
                  name: worker-1
                  labels:
                    node-role.kubernetes.io/infra: ""
                    node-role.kubernetes.io/worker-:
            - complianceType: musthave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfigPool
                metadata:
                  name: infra
                spec:
                  machineConfigSelector:
                    matchExpressions:
                      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,infra]}
                  nodeSelector:
                    matchLabels:
                      node-role.kubernetes.io/infra: ""
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Scheduler
                metadata:
                  name: cluster
                spec:
                  mastersSchedulable: false
                  defaultNodeSelector: "node-role.kubernetes.io/worker="
