apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-infra-nodes
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-infra-nodes
      spec:
        remediationAction: enforce
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["custom-policies"]
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Node
            metadata:
              name: worker-2
              labels:
                node-role.kubernetes.io/infra: ""
                node-role.kubernetes.io/worker-:
