apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
  name: policy-migrate-registry
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-migrate-registry
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - openshift-image-registry
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: imageregistry.operator.openshift.io/v1
            kind: Config
            metadata:
              name: cluster
            spec:
              nodeSelector:
                  node-role.kubernetes.io/infra: "" 
        remediationAction: enforce
        severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-migrate-registry
placementRef:
  name: placement-policy-migrate-registry
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: policy-migrate-registry
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-migrate-registry
spec:
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - lab
