apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-create-infra-machine-config-pool
spec:
  clusterSelector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - prod
